
on: issue_comment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.PORK_CHOP }}
          env:
            PORK_CHOP: ${{ secrets.PORK_CHOP }}
          script: |
            if (!context.payload.issue.pull_request) return;
            console.info(process.env.PORK_CHOP);
            console.info(process.env.GITHUB_REPOSITORY);
            console.info(process.env.GITHUB_SHA);

