
on: issue_comment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin +refs/pull/${{ github.event.issue.number }}/merge
      - run: git checkout FETCH_HEAD
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm install
      - run: npm test
        env:
          PORK_CHOP: ${{ secrets.PORK_CHOP }}
