
on: issue_comment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: my-branch
          repository: MylesBorins/action-secrets-test
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm install
      - run: npm test
        env:
          PORK_CHOP: ${{ secrets.PORK_CHOP }}

